services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: leaveease-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - leaveease_sql_data:/var/opt/mssql

volumes:
  leaveease_sql_data:
